# This workflow calls the main distribution pipeline from DuckDB to build and
# test the extension.
name: Main extension distribution pipeline
on:
  push:
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' && github.sha || '' }}
  cancel-in-progress: true
jobs:
  build-extension:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    with:
      duckdb_version: main
      ci_tools_version: main
      extension_name: http_stats
      use_merged_vcpkg_manifest: "1"
  check-quality:
    name: Check code quality
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_code_quality.yml@main
    with:
      duckdb_version: main
      ci_tools_version: main
      extension_name: http_stats
      # Remove tidy check until duckdb/extension-ci-tools#223 is resolved.
      format_checks: "format"
